---
- hosts: WebServer
  tasks:
    - name: "Install NginX"
      apt:
        name: nginx
        state: present

    - name: "Install Certbot"
      apt:
        name: certbot
        state: present

    - name: "Start Nginx Services"
      service:
        name: nginx
        state: started

    - name: "Deploy Website"
      become: true
      synchronize:
        dest: /var/www/html
        src: ../default-web/

    - name: "Set Directory Owner"
      become: true
      file:
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: 0755
        recurse: yes

    - name: "Run Certbot for SSL"
      command: "certbot --nginx --non-interactive --agree-tos --email samadkhansk5567@gmail.com -d 35.200.200.65"
      become: true
      ignore_errors: yes  # Ignore errors in case the SSL certificate is already installed

    - name: "Reload Nginx after Certbot"
      service:
        name: nginx
        state: reloaded
